create table cards (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  question text not null,
  answer text not null,
  title text,
  page integer
);
