create table collections (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  file_name text,
  access_count integer default 0,
  created_at timestamptz default now()
);

alter table cards
add column collection_id bigint references collections(id);
